version: '3'
services:
  database:
    container_name: db
    image: mysql:8.1.0
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    env_file:
      - ./.env
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

  phpmyadmin:
    container_name: gui-admin
    image: phpmyadmin
    ports:
      - "8088:80"
    networks:
      - db
    env_file:
      - ./.env

volumes:
  data-db:

networks:
  db: